name: DGSPR
run-name: Deploy Github Static Page / React
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build
        run: |
          mkdir -p LINE-Tool-Kit/dist
          cp -r ./LINE-Tool-Kit/dist/* LINE-Tool-Kit/dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: 'LINE-Tool-Kit/dist'
          name: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact: 'dist'
